Update faq.md
vespa-engine/documentation pull request #1306
Opened 2021-05-23 10:34 UTC by 107dipan

Adding some of the queries I made in the Gitter chatroom

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-05-24 17:53 UTC, kkraune commented
Thanks @107dipan  I will review and merge tomorrow!

2021-05-25 10:29 UTC, kkraune requested changes
This is great! Please look into my suggestions before we merge. Keep these FAQ entries coming, thanks a lot for contributing, looking forward to the next one(s) :-) !

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +to be defined with indexing attribute and hence will be stored inthe memory.
```suggestion
to be defined with indexing attribute and hence will be stored in memory. 
Refer to [map](reference/schema-reference.html#type:map)
```

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +We need to implement a document processor for this
```suggestion
Implement a [document processor](document-processing.html) for this.
```

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +and a DocProc if we want to handle them in some special way on the indexing side.
```suggestion
and a [DocProc](document-processing.html) if we want to handle them in some special way on the indexing side.
```

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +It provides the building blocks but not an out of the box solution. We can write a Searcher to detect query-side entities and rewrite the query,
```suggestion
It provides the building blocks but not an out of the box solution.
We can write a [Searcher](searcher-development.html) to detect query-side entities and rewrite the query, 
```

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +You can write a document procrssor for text extraction but Vespa doesn’t provide it out of th box.
```suggestion
You can write a document processor for text extraction but Vespa doesn’t provide it out of the box.
```

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +No
```suggestion
No. Use [visiting](content/visiting.html) to dump all or a subset of documents.
See [dumping-data](https://cloud.vespa.ai/en/dumping-data) for a sample script.
```

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +#### What is the response when data is written only on some of the nodes and not on all of the replica nodes(Based on the redundancy count of the content cluster)?
```suggestion
#### What is the response when data is written only on some of the nodes and not on all of the replica nodes (Based on the redundancy count of the content cluster)? 
```

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +Yes just add a “deleted” attribute, add fast-sarch on it and create a searcher which adds an “andnot deleted” itm to queries.
```suggestion
Yes just add a "deleted" attribute, add [fast-search](attributes.html#fast-search) on it
and create a searcher which adds an “andnot deleted” item to queries.
```

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +#### Can we configure a grace period for bucket distribution so that buckets are not redistribured as soon as a node goes down?
```suggestion
#### Can we configure a grace period for bucket distribution so that buckets are not redistributed as soon as a node goes down? 
```

2021-05-25 10:29 UTC, kkraune commented on en/faq.md
> +https://docs.vespa.ai/en/reference/services-content.html#transition-time
```suggestion
You can set a [transition-time](reference/services-content.html#transition-time) in services.xml to tell the cluster controller how long a node is to be kept in maintenance mode before being automatically marked down.
```

2021-05-25 10:35 UTC, 107dipan commented on en/faq.md
> +You can write a document procrssor for text extraction but Vespa doesn’t provide it out of th box.
I have applied all your suggestions. 
Thanks a lot!

2021-05-25 10:40 UTC, kkraune commented
Thanks!

2021-05-25 10:40 UTC, merged