Add comment about no short-circuit evaluation in if statements.
vespa-engine/documentation pull request #2280
Opened 2022-09-16 10:35 UTC by baldersheim

@bratseth @geirst @havardpe @kkraune PR

2022-09-16 10:45 UTC, bratseth requested changes
👍 just remove the duplicate line

2022-09-16 10:45 UTC, bratseth commented on en/reference/ranking-expressions.html
> +Note that there is <em>no short-circuit</em> evaluation. Given <pre>if (cheap_expr >= 1 && expensive_expr > 1, even_more_expensive_expr, -1.0)</pre>
```suggestion
```

2022-09-16 10:52 UTC, geirst approved these changes
👍

2022-09-18 19:46 UTC, jobergum commented
Thanks for adding this to documentation!

2022-09-18 19:49 UTC, baldersheim commented
I will hold merge until we conclude on adding short-circuit evaluation.

2022-09-18 20:41 UTC, kkraune approved these changes

2022-09-18 20:41 UTC, kkraune commented on en/reference/ranking-expressions.html
> +    <tr><td>&&</td> <td>Logical AND - No short-circuit evaluation.</td></tr>
```suggestion
    <tr><td>&amp;&amp;</td> <td>Logical AND - No short-circuit evaluation.</td></tr>
```

2022-09-20 15:23 UTC, bratseth commented
Implementet instead, closing.

2022-09-20 15:23 UTC, closed without merging